project:
  type: website
  output-dir: docs

website:
  title: "FLARE (Forecasting Lake and Reservoir Ecosystems)"
  page-navigation: true
  repo-url: https://github.com/rqthomas/flare-dashboard
  repo-actions: [edit, issue]

  navbar:
    background: primary
    search: true
    left:
      - href: fcre.qmd
        icon: droplet
      - href: sunp.qmd
        icon: droplet
      - href: alex.qmd
        icon: droplet
      - href: neon.qmd
        icon: droplet
  page-footer:
    left: "CC-BY"
    right:
      - icon: github
        href: https://github.com/rqthomas/flare-dashboard

format:
  html:
    theme: [yeti, custom.scss]
    css: styles.css
    title-block-style: default
    title-block-banner: "img/fcre_long2.png"
#    title-block-banner-color: white
    page-layout: full
    toc: true

editor: visual

