project:
  type: website
  output-dir: docs

website:
  title: "EFI NEON Challenge"
  page-navigation: true
  repo-url: https://github.com/eco4cast/neon4cast-dashboard
  repo-actions: [edit, issue]

  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        icon: home
      - href: phenology.qmd
        icon: tree-fill
      - href: aquatics.qmd
        icon: droplet
      - href: terrestrial.qmd
        icon: thermometer-half
      - href: ticks.qmd
        icon: bug-fill
      - href: beetles.qmd
        icon: bug

  page-footer:
    left: "CC-BY"
    right:
      - icon: github
        href: https://github.com/eco4cast/neon4cast-dashboard

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

