---
title: "Lake Sunapee Protective Association"
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning=FALSE)
```

```{r setup}
library(ggiraph)
library(patchwork)
library(tidyverse)
library(neon4cast)
library(score4cast)


library(thematic)
thematic_rmd(bg="white", fg="black", accent="blue")

#source("R/plot-utils.R")


```

## Most recent forecasts

Text about LSPA and Lake Sunapee

::: panel-tabset
## Lake Sunapee

```{r}
s3 <- arrow::s3_bucket(bucket = "scores/parquet", endpoint_override = "s3.flare-forecast.org", anonymous = TRUE)

most_recent <-  arrow::open_dataset(s3) |> 
  filter(site_id == "sunp") |> 
  summarize(max = max(reference_datetime)) |> 
  collect() |> 
  pull()

df_insitu_scores <- arrow::open_dataset(s3) |> 
  filter(variable == "temperature",
         depth %in% c(1.0, 8.0),
         site_id == "sunp",
         reference_datetime == most_recent) |> 
  dplyr::collect()
```

The most recent forecast is from `r lubridate::with_tz(lubridate::as_datetime(most_recent), tzone = "America/New_York")`.

```{r}
## date of each team's most recent forecast
df_insitu_scores |> 
  mutate(datetime = lubridate::with_tz(datetime, "America/New_York")) |> 
  ggplot(aes(x = datetime)) +
  geom_ribbon(aes(ymin = quantile10, ymax = quantile90), fill = "lightblue", color = "lightblue") +
  geom_line(aes(y = mean)) +
  geom_point(aes(y = observation)) +
  facet_wrap(~depth) +
  labs(y = "temperature") +
  theme_bw()
```

```{r eval = FALSE}
df_horizon <- arrow::open_dataset(s3) |> 
  filter(variable == "temperature",
         site_id == "sunp",
         depth %in% c(1.0, 8.0),
         horizon %in% c(2,7,14)) |> 
  dplyr::collect()

df_horizon |> 
  ggplot(aes(x = observation, y = mean, color = horizon)) +
  geom_point() +
  geom_smooth(method = "lm") + 
  labs(x = "observed temperature", y = "forecasted temperature") +
  theme_bw()


```
:::
