# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
#      - uses: r-lib/actions/setup-renv@v1
      - name: Install
        shell: Rscript {0}
        run: |
          install.packages("remotes")
          remotes::install_deps()
      - name: Render
        shell: Rscript {0}
        run: |
          rmarkdown::render("phenology.Rmd")
      - name: Render
        shell: Rscript {0}
        run: |
          rmarkdown::render("aquatics.Rmd")
      - name: Render
        shell: Rscript {0}
        run: |
          rmarkdown::render("terrestrial.Rmd")
      - name: Render
        shell: Rscript {0}
        run: |
          rmarkdown::render("ticks.Rmd")
      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit index.html -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
